# podman compose up --build -d
services:
  server:
    build: .
    container_name: brev.ly
    ports:
      - 3333:$BACKEND_PORT
    environment:
      - CLOUDFARE_ACCOUNT_ID=$CLOUDFARE_ACCOUNT_ID
      - CLOUDFARE_ACCESS_KEY_ID=$CLOUDFARE_ACCESS_KEY_ID
      - CLOUDFARE_SECRET_ACCESS_KEY=$CLOUDFARE_SECRET_ACCESS_KEY
      - CLOUDFARE_BUCKET=$CLOUDFARE_BUCKET
      - CLOUDFARE_PUBLIC_URL=$CLOUDFARE_PUBLIC_URL
      - DATABASE_URL=$DB_CONTAINER_URL
    networks:
      - server
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - server
      - db

volumes:
  db:
    driver: local
networks:
  server:
    driver: bridge
  db:
    driver: bridge
